---
- name: Check rsyslog.conf for cmdlog and iptables logs
  shell: |
    files=("/var/log/cmdlog.log" "/var/log/iptables/iptables.log")
    for file in "${files[@]}"; do
      if grep -v ^# /etc/rsyslog.conf | grep -qw "$file"; then
        echo "$file ==> OK"
      else
        echo "$file ==> WARNING"
      fi
    done
  register: rsyslog_check
  ignore_errors: yes
  args:
    executable: /bin/bash

- name: Display rsyslog configuration status for cmdlog and iptables logs
  debug:
    msg: "{{ rsyslog_check.stdout_lines }}"

- name: Check rsyslog.conf for cmdlog logging
  shell: |
    rsyslog_cmdlog_check=$(grep -v ^# /etc/rsyslog.conf | grep "local6" | grep "/var/log/cmdlog.log" | wc -l)
    if [[ $rsyslog_cmdlog_check == 0 ]]; then
      echo "rsyslog.conf not configured for cmd logging ==> WARNING"
    elif [[ $rsyslog_cmdlog_check == 1 ]]; then
      echo "rsyslog.conf configured for cmd logging ==> OK"
    else
      echo "rsyslog.conf has duplicate cmd logging configuration ==> WARNING"
    fi
  register: rsyslog_cmdlog_check
  ignore_errors: yes
  args:
    executable: /bin/bash

- name: Display rsyslog cmdlog configuration status
  debug:
    msg: "{{ rsyslog_cmdlog_check.stdout_lines }}"
