---
- name: Check for server multipath
  ansible.builtin.command: |
    bash -c '
    multipath_list=$(dmsetup status | grep -vw linear | awk "{print \$1}" | sed -e "s/://g" | grep -v p[0-9]$ | grep -v No)
    if [[ -z "$multipath_list" ]]; then
        echo "Server has no multipath ==> OK"
    else
        for line in $multipath_list; do
            path_count=$(multipath -ll "$line" | grep -c running)
            if [[ $path_count -lt 4 ]]; then
                echo "Server has line $line with $path_count path running < 4 ==> WARNING"
            else
                echo "Server has line $line with $path_count path running >= 4 ==> OK"
            fi
        done
    fi
    '
  register: multipath_check
  ignore_errors: true

- name: Show multipath check result
  debug:
    var: multipath_check.stdout_lines
