---
- name: Check swap configuration
  shell: tail -n+2 /proc/swaps
  register: swap_check_output
  ignore_errors: yes

- name: Display swap configuration status
  debug:
    msg: >-
      Check swap configuration:{% if swap_check_output.stdout.strip() == '' %}
      No swap partition found ==> WARNING{% else %}
      Swap partition found ==> OK{% endif %}

- name: Check swappiness configuration
  shell: cat /proc/sys/vm/swappiness
  register: swappiness_output
  ignore_errors: yes

- name: Display swappiness configuration status
  debug:
    msg: >-
      Check swappiness configuration:{% if swappiness_output.stdout.strip() == '' or swappiness_output.stdout | int > 10 %}
      Swappiness is incorrectly configured: Swappiness={{ swappiness_output.stdout.strip() }} ==> WARNING{% else %}
      Swappiness is correctly configured: Swappiness={{ swappiness_output.stdout.strip() }} ==> OK{% endif %}

