---
- name: Get list of users in the system
  shell: |
    awk -F: '($7 == "/bin/bash" && $3 >= 400) {print $1}' /etc/passwd
  register: user_list
  failed_when: false

- name: Check nproc configuration for each user
  debug:
    msg: >-
      {% for user in user_list.stdout_lines %}
      {% set nproc_check = lookup('file', '/etc/security/limits.conf') | regex_search('^' ~ user ~ '.*nproc') %}
      {% if nproc_check %}User {{ user }}: {{ nproc_check }} ==> OK
      {% else %}User {{ user }}: nproc not configured ==> WARNING
      {% endif %}
      {% endfor %}
  loop: "{{ user_list.stdout_lines }}"
