- name: Check for unowned files
  shell: |
    find / -xdev \( -nouser -o -nogroup \) -print
  register: unowned_files
  changed_when: false

- name: Convert unowned files output to a list
  set_fact:
    unowned_files_list: "{{ unowned_files.stdout_lines }}"

- name: Display unowned files if found
  debug:
    msg:
      -  Unowned files were found, check path ==> WARNING
      - "{{ unowned_files_list }}"
  when: unowned_files_list | length > 0

- name: Report if no unowned files are found
  debug:
    msg: "No unowned files found ==> OK"
  when: unowned_files_list | length == 0
